/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-08-21 19:34:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.usuario;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/programacao%20if/site%20matérias/prjModulo8/prjModulo81/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/prjModulo8/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1631274532000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-BR\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Página de Cadastro</title>\n");
      out.write("    <!-- fizemos o css em um arquivo separado, porém ele não estava sendo chamado após a configuração do filter,\n");
      out.write("    	portanto fizemos dentro do jsp.\n");
      out.write("     -->\n");
      out.write("	<style type=\"text/css\">\n");
      out.write("		*{\n");
      out.write("		    padding: 0;\n");
      out.write("		    margin: 0;\n");
      out.write("		    box-sizing: border-box;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		body {\n");
      out.write("		    color: #000;\n");
      out.write("		    overflow-x: hidden;\n");
      out.write("		    height: 100vh;\n");
      out.write("		    background-image: linear-gradient(to right, #30a130,#3883b6);\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		#nome, #email, #senha{\n");
      out.write("		    background-color: #F3E5F5;\n");
      out.write("		    border-radius: 50px;\n");
      out.write("		    padding: 12px 15px 12px 15px;\n");
      out.write("		    width: 100%;\n");
      out.write("		    box-sizing: border-box;\n");
      out.write("		    border: none;\n");
      out.write("		    border: 1px solid #F3E5F5;\n");
      out.write("		    font-size: 16px;\n");
      out.write("		    color: #000;\n");
      out.write("		    font-weight: 400;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		#nome:focus, #email:focus, #senha:focus{\n");
      out.write("		    -moz-box-shadow: none;\n");
      out.write("		    -webkit-box-shadow: none;\n");
      out.write("		    box-shadow: none;\n");
      out.write("		    border: 1px solid #30a130;\n");
      out.write("		    outline-width: 0;\n");
      out.write("		    font-weight: 400;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		#btn2 {\n");
      out.write("		    width: 150px;\n");
      out.write("		    box-sizing: border-box;\n");
      out.write("		    border-radius: 50px;\n");
      out.write("		    color: #fff;\n");
      out.write("		    background-image: linear-gradient(to right, #575757,#151615);\n");
      out.write("		    padding: 15px;\n");
      out.write("		    cursor: pointer;\n");
      out.write("		    border: none;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		#btn2:hover {\n");
      out.write("		    box-sizing: border-box;\n");
      out.write("		    border-radius: 50px;\n");
      out.write("		    color: #fff;\n");
      out.write("		    background-image: linear-gradient(to right, #151615,#575757);\n");
      out.write("		    padding: 15px;\n");
      out.write("		    cursor: pointer;\n");
      out.write("		    border: none;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.form-control-label {\n");
      out.write("		    font-size: 12px;\n");
      out.write("		    margin-left: 15px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.msg-info {\n");
      out.write("		    padding-left: 15px;\n");
      out.write("		    margin-bottom: 30px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.btn-color {\n");
      out.write("		    border-radius: 50px;\n");
      out.write("		    color: #fff;\n");
      out.write("		    background-image: linear-gradient(to right, #3883b6,#53d353);\n");
      out.write("		    padding: 15px;\n");
      out.write("		    cursor: pointer;\n");
      out.write("		    border: none;\n");
      out.write("		    margin-top: 40px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.btn-color:hover {\n");
      out.write("		    color: #fff;\n");
      out.write("		    background-image: linear-gradient(to right, #30a130,#3883b6 );\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		.sm-text {\n");
      out.write("		    font-size: 15px;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		@media screen and (max-width: 992px) {\n");
      out.write("		\n");
      out.write("		    .card1 {\n");
      out.write("		        width: 100%;\n");
      out.write("		        padding: 40px 30px 10px 30px;\n");
      out.write("		        margin: auto;\n");
      out.write("		    }\n");
      out.write("		    .card2 {\n");
      out.write("		        width: 100%;\n");
      out.write("		        margin: auto;\n");
      out.write("		    }\n");
      out.write("		    .right {\n");
      out.write("		        margin-top: 100px;\n");
      out.write("		        margin-bottom: 100px;\n");
      out.write("		    }\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		@media screen and (max-width: 668px) {\n");
      out.write("		\n");
      out.write("		    .container {\n");
      out.write("		        padding: 10px;\n");
      out.write("		        margin: auto;\n");
      out.write("		    }\n");
      out.write("		    .card2 {\n");
      out.write("		        padding: 50px;\n");
      out.write("		        margin: auto;\n");
      out.write("		    }\n");
      out.write("		    .right {\n");
      out.write("		        margin-top: 50px;\n");
      out.write("		        margin-bottom: 50px;\n");
      out.write("		        margin: auto;\n");
      out.write("		    }\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1\" crossorigin=\"anonymous\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <section id=\"login\" class=\"container\" style=\"margin-top: 20px;\">\n");
      out.write("        <form action=\"registro\" method=\"post\" style=\"margin-left: auto; margin-right: auto;\">\n");
      out.write("            <div class=\"container px-4 py-5 mx-auto row\">\n");
      out.write("            <div class=\"card card1 row\" style=\"width: 400px; margin: auto; margin-top: -10px;\">\n");
      out.write("                <div class=\"row justify-content-center my-auto\" style=\"padding: 30px, 15px;\">\n");
      out.write("                    <div class=\"col-md-8 col-10 my-5\">\n");
      out.write("                        <h4 class=\"mb-5 text-center heading display-6\">Bem vindo!</h4>\n");
      out.write("                        <div class=\"text-center\">\n");
      out.write(" 	                       <h6 class=\"msg-info\" style=\"font-weight: 400;\">Crie uma nova conta</h6>\n");
      out.write("                        </div>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        <div class=\"form-group\"> \n");
      out.write("                        	<label class=\"form-control-label text-muted\">Nome</label> \n");
      out.write("                        	<input type=\"text\" id=\"nome\" name=\"nome\" placeholder=\"seu nome\" class=\"form-control\" style=\"background-color: rgb(231, 222, 222);\" required=\"required\"> \n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                        	<label class=\"form-control-label text-muted\">Email</label>\n");
      out.write("                        	<input type=\"email\" id=\"email\" name=\"email\" placeholder=\"email@gmail.com\" class=\"form-control\" style=\"background-color: rgb(231, 222, 222);\" required=\"required\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"form-group\">\n");
      out.write("                        	<label class=\"form-control-label text-muted\">Senha</label>\n");
      out.write("                        	<input type=\"password\" id=\"senha\" name=\"senha\" placeholder=\"senha\" class=\"form-control\" style=\"background-color: rgb(231, 222, 222);\" required=\"required\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"row justify-content-center my-3 px-3\">\n");
      out.write("                        	<button class=\"btn-block btn-color\" style=\"margin-top: 15px;\">Cadastrar</button>\n");
      out.write("                        </div>\n");
      out.write("                    	<a href=\"../index.jsp\" class=\"btn btn-secondary\" id=\"btn2\" style=\"margin-left: 32px;\">Voltar</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>        \n");
      out.write("            </div>    \n");
      out.write("        </div>\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW\" crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /usuario/cadastro.jsp(146,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mensagem1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	                        <div class=\"alert alert-success text-center\" role=\"alert\">\n");
          out.write("	                        	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensagem1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("	                        </div>\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /usuario/cadastro.jsp(151,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty mensagem2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	                        <div class=\"alert alert-danger text-center\" role=\"alert\">\n");
          out.write("	                        	");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensagem2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\n");
          out.write("	                        </div>\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
