/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-08-21 19:35:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.usuario;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listagem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/programacao%20if/site%20matérias/prjModulo8/prjModulo81/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/prjModulo8/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153395882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1631274532000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Página de listagem</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU\" crossorigin=\"anonymous\">\n");
      out.write("<style>\n");
      out.write("        *{\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #logout{\n");
      out.write("            padding: 1px;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab{\n");
      out.write("            margin-top: 50px;\n");
      out.write("            margin: auto;\n");
      out.write("            max-width: 85vw;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #tab tr:hover{\n");
      out.write("            background: rgb(207, 206, 206);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #bot{\n");
      out.write("            width: 100px;\n");
      out.write("            margin-top: 25px;\n");
      out.write("            margin-left: auto;\n");
      out.write("            margin-right: auto;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #bot_bot{\n");
      out.write("            width: 100px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #delete{\n");
      out.write("            background-color: rgb(255, 111, 111);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #edit{\n");
      out.write("            background-color: rgb(219, 219, 68);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #delete:hover{\n");
      out.write("             background-color: rgb(204, 56, 56);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        #edit:hover{\n");
      out.write("             background-color: rgb(206, 172, 61);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .modal_classe{\n");
      out.write("            width: 100vw;\n");
      out.write("            height: 100vh;\n");
      out.write("            background-color: rgba(0, 0, 0, 0.555);\n");
      out.write("            position: fixed;\n");
      out.write("            top: 0px;\n");
      out.write("            left: 0px;\n");
      out.write("            z-index: 2000;\n");
      out.write("            display: none;\n");
      out.write("            justify-content: center;\n");
      out.write("            align-items: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal_classe.mostrar{\n");
      out.write("            display: flex;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .modal_legal{\n");
      out.write("            padding: 30px;\n");
      out.write("            width: 400px;\n");
      out.write("            min-width: 300px; \n");
      out.write("            box-shadow: 0px 0px 15px rgb(68, 68, 68);\n");
      out.write("            border-radius: 5px;\n");
      out.write("            background-color: white;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes modal {\n");
      out.write("            from{\n");
      out.write("              opacity: 0;\n");
      out.write("              transform: translate3d(0, 60px, 0);\n");
      out.write("            }\n");
      out.write("            to{\n");
      out.write("              opacity: 1;\n");
      out.write("              transform: translate3d(0, 0, 0);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .mostrar .modal_legal{\n");
      out.write("            animation: modal .3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .fechar{\n");
      out.write("            position: absolute;\n");
      out.write("            top: 12px;\n");
      out.write("            right: 12px;\n");
      out.write("            width: 20px;\n");
      out.write("            background: white;\n");
      out.write("            cursor: pointer;\n");
      out.write("            border: 4px solid white\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");


String email = (String) session.getAttribute("email");

if(email == null) {
	response.sendRedirect("../index.jsp");
	
}


      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container my-4\" style=\"max-width: 850px;\">\n");
      out.write("	<h1 class=\"display-4\" style=\"text-align: center; margin-top: 18px;\">Matérias Cadastradas</h1>\n");
      out.write("	<br>\n");
      out.write("\n");
      out.write("	<div id=\"logout\">\n");
      out.write("	    <button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Adicionar</button>\n");
      out.write("	    <button type=\"button\" class=\"btn btn-primary\" onclick=\"notificar()\" >Notificar</button>\n");
      out.write("	    \n");
      out.write("        <a id=\"edit\" class=\"btn tooltip-test\" title=\"Editar Usuario\" style=\"margin-left: 66%;\" href=\"editarUsuario?nome=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${usuario.nome}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Editar</a>\n");
      out.write("       \n");
      out.write("		<a href=\"usuario/deslogar.jsp\" id=\"des\" class=\"btn btn-secondary\" style=\"margin-left: 2%; \">Deslogar</a>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Matérias</h5>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("        <form id=\"form-adicionar\" action=\"enviar\">\n");
      out.write("          <div class=\"mb-3\">\n");
      out.write("            <label for=\"recipient-name\" class=\"col-form-label\">Titulo</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"recipient-name\" name=\"titulo\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"mb-3\">\n");
      out.write("            <label for=\"message-text\" class=\"col-form-label\">Descrição</label>\n");
      out.write("            <textarea name=\"descricao\" class=\"form-control\" id=\"message-text\"></textarea>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("        <button type=\"submit\" form=\"form-adicionar\" class=\"btn btn-primary\">Salvar</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<hr>\n");
      out.write("	\n");
      out.write("	<div id=\"table_bx\">\n");
      out.write("   <table class=\"table table-bordered\" id=\"tab\">\n");
      out.write("       <thead class=\"table-dark\">\n");
      out.write("         <tr>\n");
      out.write("           <th scope=\"col\">Matéria</th>\n");
      out.write("           <th scope=\"col\">Descrição</th>\n");
      out.write("           <th scope=\"col\">ID</th>\n");
      out.write("           <th scope=\"col\"></th>\n");
      out.write("         </tr>\n");
      out.write("       </thead>\n");
      out.write("       <tbody>\n");
      out.write("          ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      </tbody>\n");
      out.write("    </table>\n");
      out.write("    </div>\n");
      out.write("	<div id=\"bot\">\n");
      out.write("		<a href=\"index.jsp\" id=\"bot_bot\" class=\"btn btn-secondary\">Voltar</a>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("//funcao pra testar notificação\n");
      out.write("function showNotification(){\n");
      out.write("    \n");
      out.write("    const notification = new Notification(\"Notificação !\", {\n");
      out.write("        body:\"Voce tem atividades pendentes !\"\n");
      out.write("    })\n");
      out.write("}\n");
      out.write("\n");
      out.write("function notificar(){\n");
      out.write("	if(Notification.permission === \"granted\"){\n");
      out.write("    showNotification()\n");
      out.write("  }else if(Notification.permission !== \"denied\"){\n");
      out.write("    Notification.requestPermission().then(permission => {\n");
      out.write("        if(permission === \"granted\"){\n");
      out.write("            showNotification()\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function setaDadosModal(valor) {\n");
      out.write("	\n");
      out.write("	document.getElementById('nome-materia').innerHTML = 'Tem certeza que deseja excluir ' + '\"' + valor + '\"' + ' ?';\n");
      out.write("	document.getElementById('campo').value = valor;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ\" crossorigin=\"anonymous\"></script>           		\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /usuario/listagem.jsp(178,10) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("contagem");
      // /usuario/listagem.jsp(178,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/usuario/listagem.jsp(178,10) '${materias}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${materias}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /usuario/listagem.jsp(178,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("materia");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                <tr>\n");
            out.write("                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.titulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.descricao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                  <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                <td>\n");
            out.write("                  	<div class=\"container\">\n");
            out.write("                  		<div class=\"row\">\n");
            out.write("                  			<div class=\"col-md-6 p-0\">\n");
            out.write("                  				<a id=\"edit\" class=\"btn tooltip-test\" title=\"Editar Matéria\" href=\"editar?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><i class=\"bi bi-pencil-square\"></i></a>\n");
            out.write("                  			</div>\n");
            out.write("                  			<div class=\"col-md-6 p-0\" >\n");
            out.write("                  			    \n");
            out.write("           \n");
            out.write("                  			      \n");
            out.write("								   <a type=\"submit\" id=\"delete\" onclick=\"setaDadosModal('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${materia.titulo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("')\" data-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\" title=\"Excluir Matéria\" class=\"btn delete tooltip-test\">\n");
            out.write("								     <i class=\"bi bi-trash\"></i>\n");
            out.write("								   </a>\n");
            out.write("                  			    \n");
            out.write("                  			    \n");
            out.write("								\n");
            out.write("								<!-- Modal -->\n");
            out.write("								\n");
            out.write("							\n");
            out.write("								<div class=\"modal fade\" id=\"staticBackdrop\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
            out.write("								  <div class=\"modal-dialog modal-dialog-centered\">\n");
            out.write("								    <div class=\"modal-content\">\n");
            out.write("								      <div class=\"modal-header\">\n");
            out.write("								        <h5 class=\"modal-title\" id=\"staticBackdropLabel\">Modal title</h5>\n");
            out.write("								        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
            out.write("								      </div>\n");
            out.write("								      <div class=\"modal-body\">\n");
            out.write("								        <p id=\"nome-materia\">Tem certeza que deseja excluir  ?</p>\n");
            out.write("								      </div>\n");
            out.write("								      <div class=\"modal-footer\">\n");
            out.write("								        \n");
            out.write("								        <form action=\"deletar\">\n");
            out.write("								            <input class=\"d-none\" type=\"text\" name=\"titulo\" id=\"campo\">\n");
            out.write("								            <button type=\"submit\" class=\"btn btn-primary\">Excluir</button>\n");
            out.write("								        </form>\n");
            out.write("								        \n");
            out.write("								        \n");
            out.write("								      </div>\n");
            out.write("								    </div>\n");
            out.write("								  </div>\n");
            out.write("								</div>\n");
            out.write("							\n");
            out.write("								\n");
            out.write("                  			</div>\n");
            out.write("                  		</div>\n");
            out.write("                  	</div>\n");
            out.write("                  </td>\n");
            out.write("                </tr> \n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
